### PR TITLE
Feature/ch7135/add issues template

### PR DESCRIPTION
**Pull request by Eseoghene**

### CODE REVIEW

**Review by oed — CHANGES_REQUESTED** [review]

**Comment by Eseoghene** [comment]
made changes as requested by oed

**Comment by Eseoghene** [comment]
@oed Please review made changes

**Comment by oed** [comment]
@Eseoghene I'm unsure if this should be merged to master since it contains a bunch of other commits. Have to take a closer look at it.

**Review by oed — DISMISSED** [review]

**Review by oed — COMMENTED** [review]
@christianlundkvist @localredhead should HashMap really be in the develop branch?

@Eseoghene can we merge this against the develop branch and then create a new PR for master if we need to remove the HashMap contract?

**Comment by Eseoghene** [comment]
Ok merged against develop

**Pull request merged**
